### ISSUE TITLE
Cannot run successfully

### ISSUE THREAD

**Issue by sotiris-bos** [wilmardo/migrate-plex-to-jellyfin#28]
Hello, I am trying to run the script but I get this error:

```
Traceback (most recent call last):
  File "migrate.py", line 110, in <module>
    migrate()
  File "/root/git/migrate-plex-to-jellyfin/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/git/migrate-plex-to-jellyfin/venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/git/migrate-plex-to-jellyfin/venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/git/migrate-plex-to-jellyfin/venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "migrate.py", line 60, in migrate
    if source["Path"] not in jf_entries:
KeyError: 'Path'
```

I have tried with python 3.12 and 3.8.

What might the problem be?

**Comment by phazejeff** [comment]
same issue here, using docker

**Comment by phazejeff** [comment]
made a quick fix, you can use my branch until the original dev merges
