### ISSUE TITLE
plexapi.exceptions.NotFound: Invalid library section: Films

### ISSUE THREAD

**Issue by inputsh** [wilmardo/migrate-plex-to-jellyfin#9]
I've tried following the README as much as possible and ended up with this error. Couldn't find any related issues. Any tips?

```
Traceback (most recent call last):
  File "migrate.py", line 123, in <module>
    migrate()
  File "/home/<user>/migrate-plex-to-jellyfin/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/<user>/migrate-plex-to-jellyfin/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/<user>/migrate-plex-to-jellyfin/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/<user>/migrate-plex-to-jellyfin/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "migrate.py", line 53, in migrate
    plex_movies = plex.library.section('Films')
  File "/home/<user>/migrate-plex-to-jellyfin/venv/lib/python3.8/site-packages/plexapi/library.py", line 57, in section
    raise NotFound('Invalid library section: %s' % title)
plexapi.exceptions.NotFound: Invalid library section: Films
```

**Comment by wilmardo** [comment]
Yeah this should be the result of the hardcoded Plex library name here:

https://github.com/wilmardo/migrate-plex-to-jellyfin/blob/8d6b7d96f5ace2ea1944920c8bbd7de44d74dafd/migrate.py#L53

As a quickfix you can change the name to the name of your Movies library. This might also be needed for the TV shows:
https://github.com/wilmardo/migrate-plex-to-jellyfin/blob/8d6b7d96f5ace2ea1944920c8bbd7de44d74dafd/migrate.py#L60

I will tag this issue as an enhancement to pick up as an improvement sometime in the future :)
